[versions]
kotlin = "2.4.0"
detekt = "1.23.8"
coroutines = "1.11.0"
nmcp = "1.5.0"
ktor = "3.0.3"
slf4j = "2.0.18"
javaTargetCore = "17"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
ktor-network = { group = "io.ktor", name = "ktor-network", version.ref = "ktor" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
